---
stages:
  - build
  - test
  - review
  - staging

before_script:
  - export TAG=${CI_COMMIT_SHORT_SHA}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"

hyku.build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose build web workers
    - docker-compose push web
    - docker-compose push workers
  only:
    refs:
      - merge_requests
      - main
  tags:
    - local

lint:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  allow_failure: true
  script:
    - cd /app/samvera/hyrax-webapp
    - bundle check || bundle
    - bundle exec rubocop
  only:
    refs:
      - merge_requests
  tags:
    - kubernetes

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  allow_failure: true
  variables:
    ALLOW_ANONYMOUS_LOGIN: "yes"
    CONFDIR: "/app/samvera/hyrax-webapp/solr/config"
    DATABASE_ADAPTER: postgresql
    DATABASE_NAME: hyku
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    DATABASE_HOST: db
    DATABASE_URL: postgres://postgres:postgres@db/hyku
    DATABASE_USER: postgres
    POSTGRESQL_DATABASE: hyku
    POSTGRESQL_PASSWORD: postgres
    DB_PORT: 5432
    DB_HOST: db
    FCREPO_PORT: 8080
    FCREPO_HOST: fcrepo
    FEDORA_URL: http://fcrepo:8080/fcrepo/rest
    REDIS_HOST: redis
    SETTINGS__SOLR_URL: http://admin:admin@solr:8983/solr/hyku-test
    SOLR_ADMIN_USER: admin
    SOLR_ADMIN_USERNAME: admin
    SOLR_ADMIN_PASSWORD: admin
    SOLR_CONFIGSET_NAME: hyku
    SOLR_COLLECTION_NAME: hyku-test
    SOLR_CLOUD_BOOTSTRAP: "yes"
    SOLR_ENABLE_CLOUD_MODE: "yes"
    SOLR_ENABLE_AUTHENTICATION: "yes"
    SOLR_PORT: 8983
    SOLR_HOST: solr
    SOLR_URL: http://admin:admin@solr:8983/solr/hyku-test
    SOLR_ZK_HOSTS: zk:2181
    ZOO_HEAP_SIZE: 128
    ZOO_PORT_NUMBER: 2181
    GIT_STRATEGY: none
  services:
    - name: bitnami/postgresql:12.6.0
      alias: db
    - name: samvera/fcrepo4:4.7.5
      alias: fcrepo
    - name: redis:5-alpine
      alias: redis
    - name: bitnami/zookeeper:3
      alias: zk
    - name: bitnami/solr:8
      alias: solr
    - name: selenium/standalone-chrome:3.141
      alias: chrome
  before_script:
    - >-
      solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/config;
      solrcloud-assign-configset.sh;
  script:
    - cd /app/samvera/hyrax-webapp && bundle exec rspec spec/models
  only:
    refs:
      - merge_requests
      - main
  tags:
    - kubernetes

hyku.review:
  stage: review
  needs: ["hyku.build"]
  extends:
    - .deploy
  environment:
    name: hyku.review/$CI_MERGE_REQUEST_ID
    url: http://adl-hyku-$CI_MERGE_REQUEST_ID.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: hyku.review.stop
    auto_stop_in: 1 day
  only:
    refs:
      - merge_requests
  variables:
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE
    DEPLOY_TAG: $CI_COMMIT_SHORT_SHA
    WORKER_IMAGE: ${CI_REGISTRY_IMAGE}/workers
    HELM_EXPERIMENTAL_OCI: 1
    HELM_RELEASE_NAME: hyku-$CI_MERGE_REQUEST_ID
    KUBE_NAMESPACE: adl-review
    HELM_EXTRA_ARGS: >
      --values ops/review-deploys.yaml
      --set ingress.enabled=true
      --set ingress.hosts[0].host=adl-hyku-$CI_MERGE_REQUEST_ID.notch8.cloud
      --set ingress.hosts[0].paths[0].path="/"
      --set ingress.hosts[1].host=*.adl-hyku-$CI_MERGE_REQUEST_ID.notch8.cloud
      --set ingress.hosts[1].paths[0].path="/"
      --set extraEnvVars[0].name=SETTINGS__MULTITENANCY__ADMIN_HOST
      --set extraEnvVars[0].value=adl-hyku-$CI_MERGE_REQUEST_ID.notch8.cloud
      --set extraEnvVars[1].name=SETTINGS__MULTITENANCY__ROOT_HOST
      --set extraEnvVars[1].value=adl-hyku-$CI_MERGE_REQUEST_ID.notch8.cloud
      --set extraEnvVars[2].name=SETTINGS__MULTITENANCY__DEFAULT_HOST
      --set extraEnvVars[2].value=%{tenant}.adl-hyku-$CI_MERGE_REQUEST_ID.notch8.cloud
      --set extraEnvVars[3].name=SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION
      --set extraEnvVars[3].value="false"
      --set extraEnvVars[4].name=CONFDIR
      --set extraEnvVars[4].value="/app/samvera/hyrax-webapp/solr/config"
      --set extraEnvVars[5].name=RAILS_LOG_TO_STDOUT
      --set extraEnvVars[5].value="true"
      --set extraEnvVars[6].name=SUPER_ADMIN_EMAIL
      --set extraEnvVars[6].value="support@notch8.com"
      --set extraEnvVars[7].name=SUPER_ADMIN_PASSWORD
      --set extraEnvVars[7].value="testing123"

  script:
    - helm chart pull ghcr.io/samvera/hyrax/hyrax-helm:0.18.0
    - helm chart export ghcr.io/samvera/hyrax/hyrax-helm:0.18.0
    - deploy hyrax
  tags:
    - kubernetes

hyku.review.stop:
  stage: review
  extends:
    - .deploy
  environment:
    name: hyku.review/$CI_MERGE_REQUEST_ID
    url: http://hyku-$CI_MERGE_REQUEST_ID.$KUBE_INGRESS_BASE_DOMAIN
    action: stop
  when: manual
  allow_failure: true
  variables:
    HELM_RELEASE_NAME: hyku-$CI_MERGE_REQUEST_ID
    KUBE_NAMESPACE: adl-review
    GIT_STRATEGY: none
  script:
    - delete
  only:
    refs:
      - merge_requests
  tags:
    - kubernetes

hyku.staging:
  stage: staging
  extends:
    - .deploy
  environment:
    name: hyku.staging
    url: http://adl-hyku-staging.notch8.cloud
    on_stop: hyku.staging.stop
  only:
    refs:
      - main
  variables:
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE
    DEPLOY_TAG: $CI_COMMIT_SHORT_SHA
    WORKER_IMAGE: ${CI_REGISTRY_IMAGE}/workers
    HELM_EXPERIMENTAL_OCI: 1
    HELM_RELEASE_NAME: hyku-staging
    KUBE_NAMESPACE: adl-staging
    HELM_EXTRA_ARGS: >
      --values ops/staging-deploy.yaml
  script:
    - helm chart pull ghcr.io/samvera/hyrax/hyrax-helm:0.18.0
    - helm chart export ghcr.io/samvera/hyrax/hyrax-helm:0.18.0
    - deploy hyrax
  tags:
    - kubernetes

hyku.staging.stop:
  stage: staging
  extends:
    - .deploy
  environment:
    name: hyku.staging
    url: http://adlhyku-staging.$KUBE_INGRESS_BASE_DOMAIN
    action: stop
  when: manual
  allow_failure: true
  variables:
    HELM_RELEASE_NAME: hyku-staging
    KUBE_NAMESPACE: adl-staging
    GIT_STRATEGY: none
  script:
    - delete
  tags:
    - kubernetes

.deploy_helpers: &deploy_helpers |
  function deploy() {
    helm repo update

    chart="${1}"

    helm upgrade \
        --kubeconfig $KUBECONFIG_R2 \
        --install \
        --atomic \
        --timeout 15m0s \
        --set image.repository="$DEPLOY_IMAGE" \
        --set image.tag="$DEPLOY_TAG" \
        --set worker.image.repository="$WORKER_IMAGE" \
        --set worker.image.tag="$DEPLOY_TAG" \
        $HELM_EXTRA_ARGS \
        --namespace="$KUBE_NAMESPACE" \
        --create-namespace \
        "$HELM_RELEASE_NAME" \
        "${chart}"
  }

  function delete() {
    echo "Deleting release: $HELM_RELEASE_NAME..."
    helm --kubeconfig $KUBECONFIG_R2 --namespace "$KUBE_NAMESPACE" delete "$HELM_RELEASE_NAME"
  }

.deploy:
  image: dtzar/helm-kubectl:3.5.3
  before_script:
    - *deploy_helpers
