# Turn on RSpec cops
require: rubocop-rspec
inherit_from: .rubocop_todo.yml

# With the rubocop 0.47.0 and rubocop-rspec 1.8.0 the following stderr message was sent:
#   An error occurred while RSpec/DescribedClass cop was inspecting path/to/file
RSpec/DescribedClass:
  Enabled: false

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - '.internal_test_app/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/internal/**/*'
    - 'spec/test_app_templates/**/*'
    - 'Rakefile'
    - 'lib/tasks/rubocop.rake'
    # disabling collections controller as most of the rubocop errors are in hyrax
    - 'app/controllers/hyrax/dashboard/collections_controller.rb'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'app/matchers/bulkrax/application_matcher.rb'

Lint/UnusedBlockArgument:
  Exclude:
    - 'app/models/concerns/bulkrax/has_local_processing.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/indexers/hyrax/file_set_indexer.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/adventist_metadata.rb'
    - 'config/initializers/bulkrax.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/hyrax/file_sets_controller.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/hyrax/file_sets_controller.rb'
    - 'app/controllers/hyrax/my/collections_controller.rb'
    - 'app/models/adventist_metadata.rb'
    - 'app/services/hyrax/collection_types/permissions_service.rb'
    - 'spec/controllers/curation_concerns/generic_works_controller_spec.rb'
    - 'spec/features/facet_by_year_spec.rb'
    - 'spec/services/iiif_collection_thumbnail_path_service_spec.rb'
    - 'spec/services/iiif_work_thumbnail_path_service_spec.rb'
    - 'spec/routing/proprietor/accounts_routing_spec.rb'
    - 'app/actors/hyrax/actors/create_with_remote_files_actor.rb'
    - 'app/actors/hyrax/actors/file_set_actor.rb'
    - 'app/matchers/bulkrax/application_matcher.rb'
    - 'app/models/concerns/bulkrax/file_factory.rb'
    - 'app/models/concerns/bulkrax/has_matchers.rb'
    - 'config/initializers/bulkrax.rb'
    - 'app/models/concerns/bulkrax/has_local_processing.rb'
    - 'app/services/hyrax/manifest_builder_service.rb'

Metrics/ModuleLength:
  Max: 200

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Whitelist:
    - find_by_user_key
  Exclude:
    - 'lib/importer/factory/object_factory.rb'

Rails/FilePath:
  Exclude:
    - 'spec/routing/**/*'

Rails/FindBy:
  Exclude:
    - 'app/models/concerns/bulkrax/has_local_processing.rb'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/Presence:
  Exclude:
    - 'app/actors/hyrax/actors/file_set_actor.rb'
    - 'app/indexers/hyrax/file_set_indexer.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/hyku/registrations_controller_spec.rb'

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/tasks/**/*'

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/ExampleLength:
  Max: 16
  Exclude:
    - 'spec/features/facet_by_year_spec.rb'
    - 'spec/requests/date_range_limit_spec.rb'

# By default RSpec/MessageSpies has the following:
# Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/authorities/qa/authorities/collections.rb'
    - 'app/authorities/qa/authorities/find_works.rb'
    - 'app/controllers/hyrax/homepage_controller.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/actors/hyrax/actors/create_with_remote_files_actor.rb'
    - 'app/actors/hyrax/actors/file_set_actor.rb'
    - 'app/indexers/hyrax/file_set_indexer.rb'
    - 'app/models/concerns/hyrax/file_set_behavior.rb'

Style/GuardClause:
  Exclude:
    - 'app/search_builders/adv_search_builder.rb'
    - 'app/models/concerns/bulkrax/has_local_processing.rb'

Style/SymbolProc:
  Exclude:
    - 'app/models/concerns/bulkrax/has_local_processing.rb'

Style/RedundantReturn:
  Exclude:
    - 'app/matchers/bulkrax/application_matcher.rb'
    - 'app/models/concerns/bulkrax/has_matchers.rb'

Style/RedundantSelf:
  Exclude:
    - 'app/matchers/bulkrax/application_matcher.rb'
    - 'app/models/bulkrax/oai_adventist_qdc_entry.rb'
    - 'app/models/concerns/bulkrax/has_local_processing.rb'

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
