version: '2'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  zk1:
  zk2:
  zk3:
  zkconf:
  app:
  assets:

networks:
  internal:

services:
  zoo1:
    image: zookeeper:3.4
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk1:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
  zoo2:
    image: zookeeper:3.4
    restart: always
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk2:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
  zoo3:
    image: zookeeper:3.4
    restart: always
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk3:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster

  solr:
    image: solr:7.1
    command: solr -c -f -z zookeeper_cluster:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    expose:
      - 8983
    volumes:
      - solr:/opt/solr/server/solr
    networks:
      internal:

  fcrepo:
    image: cbeer/fcrepo4:4.7
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - fcrepo:/data
    environment:
      # - JAVA_OPTS=-Dfcrepo.modeshape.configuration="classpath:/config/jdbc-postgresql-s3/repository.json" -Dfcrepo.postgresql.host="db" -Dfcrepo.postgresql.username="postgres" -Dfcrepo.postgresql.password="DatabaseFTW" -Daws.accessKeyId="REPLACE_WITH_AWS_ID" -Daws.secretKey="REPLACE_WITH_AWS_SECRET_KEY" -Daws.bucket="REPLACE_WITH_BUCKET_NAME"
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      internal:

  db:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  app:
    image: hyku/main:latest
    env_file:
      - .env
    environment:
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - IN_DOCKER=true
      - LD_LIBRARY_PATH=/opt/fits/tools/mediainfo/linux
      - PASSENGER_APP_ENV=production
      - RAILS_CACHE_STORE_URL=memcache
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_HOST=redis
      - SECRET_KEY_BASE=asdf
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - SETTINGS__FITS_PATH=/opt/fits/fits.sh
      - SETTINGS__MULTITENANCY__ADMIN_HOST=hyku.docker
      - SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION=false
      - SETTINGS__MULTITENANCY__DEFAULT_HOST=%{tenant}.hyku.docker
      - SETTINGS__MULTITENANCY__ENABLED=true
      - SETTINGS__SOLR__URL=http://solr:8983/solr/
      - SOLR_URL=http://solr:8983/solr/
    volumes:
      - app:/home/app/webapp/tmp/uploads
      - assets:/home/app/webapp/public/assets
    networks:
      internal:

  web:
    extends:
      service: app
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - zoo2
      - zoo3
      - memcache
      - initialize_app
      - db_migrate
    expose:
      - 3000

  workers:
    extends:
      service: app
    command: bundle exec sidekiq
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - zoo2
      - zoo3
      - initialize_app
      - db_migrate

  initialize_app:
    extends:
      service: app
    restart: on-failure
    command: bundle exec rails zookeeper:upload
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  db_migrate:
    extends:
      service: app
    restart: on-failure
    command: bundle exec rails db:migrate
    depends_on:
      - db

  redis:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  memcache:
    image: memcached:1.5.14
    networks:
      internal:
