version: '3.8'

x-app: &app
  build:
    context: .
    target: hyku-base
    args:
      - EXTRA_APK_PACKAGES=less vim bash openjdk11-jre ffmpeg rsync
  image: registry.gitlab.com/notch8/adventist-dl:${TAG:-latest}
  env_file:
    - .env
  # NOTE: all common env variables moved to .env
  volumes:
    - uploads:/app/samvera/hyrax-webapp/public/uploads
    - assets:/app/samvera/hyrax-webapp/public/assets
    - cache:/app/samvera/hyrax-webapp/tmp/cache
    - .:/app/samvera/hyrax-webapp
  networks:
    internal:

volumes:
  fcrepo:
  solr:
  db:
  redis:
  zk1:
  zkconf:
  uploads:
  assets:
  cache:

networks:
  internal:

services:
  zoo1:
    image: zookeeper:3.4
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk1:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | nc -w 2 -q 2 localhost 2181 | grep imok || exit 1"]
      interval: "10s"
      timeout: "8"
  solr:
    image: bitnami/solr:8
    environment:
      - OOM=script
      - SOLR_ADMIN_USERNAME=admin
      - SOLR_ADMIN_PASSWORD=admin
      - SOLR_COLLECTION=hydra-development
      - SOLR_CLOUD_BOOTSTRAP=yes
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_ENABLE_AUTHENTICATION=yes
      - SOLR_PORT_NUMBER=8983
      - SOLR_ZK_HOSTS=zoo1
      - VIRTUAL_PORT=8983
      - VIRTUAL_HOST=solr.hyku.test
    depends_on:
      zoo1:
        condition: service_healthy
    expose:
      - 8983
    volumes:
      - solr:/bitnami
    networks:
      internal:

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data:cached
    env_file:
      - .env
    expose:
      - 8080
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      internal:

  db:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  web:
    <<: *app
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=hyku.test
    depends_on:
      - check_volumes
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - chrome
      - initialize_app
      - worker
    expose:
      - 3000

  worker:
    <<: *app
    build:
      context: .
      target: hyku-worker
      args:
        - EXTRA_APK_PACKAGES=less vim bash openjdk11-jre ffmpeg rsync
      cache_from:
        - registry.gitlab.com/notch8/adventist-dl:${TAG:-latest}
        - registry.gitlab.com/notch8/adventist-dl/worker:${TAG:-latest}
    image: registry.gitlab.com/notch8/adventist-dl/worker:${TAG:-latest}
    depends_on:
      - check_volumes
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - initialize_app

  # Do not recurse through all of tmp. derivitives will make booting
  # very slow and eventually just time out as data grows
  check_volumes:
    <<: *app
    user: root
    entrypoint: ["sh", "-x", "-c"]
    command:
      - >
        chown -R app:app /app/samvera/hyrax-webapp/public/uploads &&
        chown -R app:app /app/samvera/hyrax-webapp/public/assets &&
        chown -R app:app /app/samvera/hyrax-webapp/tmp/cache

  initialize_app:
    <<: *app
    environment:
      - CONFDIR=/app/samvera/hyrax-webapp/solr/config
    entrypoint: ["sh", "-c"]
    command:
      - >
        solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/config &&
        solrcloud-assign-configset.sh &&
        SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh &&
        db-migrate-seed.sh
    depends_on:
      - db
      - solr
      - fcrepo

  redis:
    image: redis:5
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  chrome:
    image: selenium/standalone-chrome:3.141
    networks:
      internal:
