version: '2.1'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  zk1:
  zkconf:
  uploads:
  assets:
  cache:

networks:
  internal:

services:
  zoo1:
    image: zookeeper:3.4
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk1:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | nc -w 2 -q 2 localhost 2181 | grep imok || exit 1"]
      interval: "10s"
      timeout: "8"
  solr:
    image: bitnami/solr:8
    environment:
      - OOM=script
      - SOLR_ADMIN_USERNAME=admin
      - SOLR_ADMIN_PASSWORD=admin
      - SOLR_COLLECTION=hydra-development
      - SOLR_CLOUD_BOOTSTRAP=yes
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_ENABLE_AUTHENTICATION=yes
      - SOLR_PORT_NUMBER=8983
      - SOLR_ZK_HOSTS=zoo1
      - VIRTUAL_PORT=8983
      - VIRTUAL_HOST=solr.hyku.test
    depends_on:
      zoo1:
        condition: service_healthy
    expose:
      - 8983
    volumes:
      - .:/app
      - solr:/opt/solr/server/solr
    networks:
      internal:

  fcrepo:
    image: cbeer/fcrepo4:4.7
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - fcrepo:/data
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      internal:

  db:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  app:
    build: .
    image: ghcr.io/samvera/hyku:latest
    env_file:
      - .env
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - FCREPO_PORT=8080
      - FCREPO_HOST=fcrepo
      - SOLR_PORT=8983
      - SOLR_HOST=solr
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - IN_DOCKER=true
      - LD_LIBRARY_PATH=/opt/fits/tools/mediainfo/linux
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_HOST=redis
      - SECRET_KEY_BASE=asdf
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - SETTINGS__BULKRAX__ENABLED=false
      - SETTINGS__FITS_PATH=/opt/fits/fits.sh
      # Comment out these 5 for single tenancy / Uncomment for multi
      - SETTINGS__MULTITENANCY__ADMIN_HOST=hyku.test
      - SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION=false
      - SETTINGS__MULTITENANCY__DEFAULT_HOST=%{tenant}.hyku.test
      - SETTINGS__MULTITENANCY__ROOT_HOST=hyku.test
      - SETTINGS__MULTITENANCY__ENABLED=false
      # Comment out these 2 for multi tenancy / Uncomment for single
      # - SETTINGS__MULTITENANCY__ROOT_HOST=hyku.test
      # - SETTINGS__MULTITENANCY__ENABLED=false
      - SETTINGS__SOLR__URL=http://admin:admin@solr:8983/solr/
      - SOLR_ADMIN_USER=admin
      - SOLR_ADMIN_PASSWORD=admin
      - SOLR_CONFIGSET_NAME=hyku
      - SOLR_URL=http://admin:admin@solr:8983/solr/
      - SOLR_COLLECTION_NAME=hydra-development
      - PASSENGER_APP_ENV=development
    volumes:
      - uploads:/app/samvera/hyrax-webapp/tmp/uploads
      - assets:/app/samvera/hyrax-webapp/public/assets
      - cache:/app/samvera/hyrax-webapp/tmp/cache
      - .:/app/samvera/hyrax-webapp
    networks:
      internal:

  web:
    extends:
      service: app
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=hyku.test
    depends_on:
      - check_volumes
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - chrome
      - initialize_app
      - db_migrate
    expose:
      - 3000

  workers:
    extends:
      service: app
    command: bundle exec sidekiq
    depends_on:
      - check_volumes
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - initialize_app
      - db_migrate


  check_volumes:
    extends:
      service: app
    user: root
    entrypoint: ["sh", "-c"]
    command:
      - >
        chown -fR app:app /app/samvera/hyrax-webapp/tmp/uploads
        chown -fR app:app /app/samvera/hyrax-webapp/public/assets
        chown -fR app:app /app/samvera/hyrax-webapp/tmp/cache

  initialize_app:
    extends:
      service: app
    environment:
      - CONFDIR=/app/samvera/hyrax-webapp/solr/config
    entrypoint: ["sh", "-c"]
    command:
      - >
        solrcloud-upload-configset.sh /app/samvera/hyrax-webapp/solr/config;
        solrcloud-assign-configset.sh;
        SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh;
    depends_on:
      - solr

  db_migrate:
    extends:
      service: app
    entrypoint: ["sh", "-c"]
    command: db-migrate-seed.sh
    depends_on:
      - db

  redis:
    image: redis:5
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  chrome:
    image: selenium/standalone-chrome:3.141
    networks:
      internal:
