version: '2.1'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  zk1:
  zkconf:
  app:
  assets:
  cache:

networks:
  internal:

services:
  zoo1:
    image: zookeeper:3.4
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk1:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | nc -w 2 -q 2 localhost 2181 | grep imok || exit 1"]
      interval: "10s"
      timeout: "8"
  solr:
    image: solr:7.5
    command: solr -c -f -z zoo1:2181
    environment:
      - OOM=script
      - VIRTUAL_PORT=8983
      - VIRTUAL_HOST=solr.hyku.docker
    depends_on:
      zoo1:
        condition: service_healthy
    expose:
      - 8983
    volumes:
      - .:/app
      - solr:/opt/solr/server/solr
    networks:
      internal:

  fcrepo:
    image: cbeer/fcrepo4:4.7
    env_file:
      - .env
    expose:
      - 8080
    volumes:
      - fcrepo:/data
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      internal:

  db:
    image: postgres:11.1
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  app:
    build: .
    image: hyku:latest
    env_file:
      - .env
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - FCREPO_PORT=8080
      - FCREPO_HOST=fcrepo
      - SOLR_PORT=8983
      - SOLR_HOST=solr
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - IN_DOCKER=true
      - LD_LIBRARY_PATH=/opt/fits/tools/mediainfo/linux
      - RAILS_LOG_TO_STDOUT=true
      - REDIS_HOST=redis
      - SECRET_KEY_BASE=asdf
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - SETTINGS__BULKRAX__ENABLED=false
      - SETTINGS__FITS_PATH=/opt/fits/fits.sh
      # Comment out these 5 for single tenancy / Uncomment for multi
      - SETTINGS__MULTITENANCY__ADMIN_HOST=hyku.docker
      - SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION=false
      - SETTINGS__MULTITENANCY__DEFAULT_HOST=%{tenant}.hyku.docker
      - SETTINGS__MULTITENANCY__ROOT_HOST=hyku.docker
      - SETTINGS__MULTITENANCY__ENABLED=true
      # Comment out these 2 for multi tenancy / Uncomment for single
      # - SETTINGS__MULTITENANCY__ROOT_HOST=hyku.docker
      # - SETTINGS__MULTITENANCY__ENABLED=false
      - SETTINGS__SOLR__URL=http://solr:8983/solr/
      - SETTINGS__ZOOKEEPER__CONNECTION_STR=zookeeper_cluster:2181/configs
      - SOLR_URL=http://solr:8983/solr/
      - PASSENGER_APP_ENV=development
    volumes:
      - app:/home/app/webapp/tmp/uploads
      - assets:/home/app/webapp/public/assets
      - cache:/home/app/webapp/tmp/cache
      - .:/home/app/webapp
    networks:
      internal:

  web:
    extends:
      service: app
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=hyku.docker
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - chrome
      - initialize_app
      - db_migrate
    expose:
      - 3000

  workers:
    extends:
      service: app
    command: bundle exec sidekiq
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - initialize_app
      - db_migrate

  initialize_app:
    extends:
      service: app
    entrypoint: ["sh", "-c"]
    command: bundle exec rails zookeeper:upload
    depends_on:
      - zoo1

  db_migrate:
    extends:
      service: app
    entrypoint: ["sh", "-c"]
    command: db-migrate-seed.sh
    depends_on:
      - db

  redis:
    image: redis:5
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  chrome:
    image: selenium/standalone-chrome:3.141
    networks:
      internal:
