terms:
  - id: published
    term: Published
    active: true
  - id: earlyonline
    term: E-Pub ahead of publication
    active: true
  - id: accepted
    term: Accepted
    active: true
  - id: submitted
    term: Submitted
    active: true
  - id: inpress
    term: In Press
    active: true
  - id: unpublished
    term: Unpublished
    active: true
