terms:
  - id: ba
    term: Bachelor of Arts (BA)
    active: true
  - id: bphil
    term: Bachelor of Philosophy (BPhil)
    active: true
  - id: bsc
    term: Bachelor of Science (BSc)
    active: true
  - id: ma
    term: Master of Arts (MA)
    active: true
  - id: mres
    term: Master of Arts by Research (MRes)
    active: true
  - id: mphil
    term: Master of Philosophy (MPhil)
    active: true
  - id: mres
    term: Master of Research (MRes)
    active: true
  - id: msc
    term: Master of Science (MSc)
    active: true
  - id: mres-s
    term: Master of Science by Research (MRes)
    active: true
  - id: phdip
    term: Postgraduate Diploma (PGDip)
    active: true
