terms:
  - id: masters-pg
    term: Masters (Postgraduate)
    active: true
  - id: diploma-pg
    term: Diploma (Postgraduate)
    active: true
  - id: bachelors-ug
    term: Bachelors (Undergraduate)
    active: true
  - id: doctoral-pg
    term: Doctoral (Postgraduate)
    active: true