# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTINGS__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#
multitenancy:
  enabled: false
  default_host: # "%{tenant}.dev"
  admin_host:
  admin_only_tenant_creation: true
  root_host:

ssl_configured: false

action_controller:
  asset_host:

redis:
  default_namespace: hyku

solr:
  url: "http://127.0.0.1:8983/solr/"
  configset: hyku
  configset_source_path: <%= File.join(Rails.root, 'solr', 'config') %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: hyku
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:

active_job:
  queue_adapter: :async

active_job_queue:
  url:

s3:
  upload_bucket:

fits_path: "fits.sh"

google_analytics_id:

# Register here: http://www.geonames.org/manageaccount
geonames_username: 'jcoyne'

# The address to which the contact form is submitted
contact_email: "change-me-in-hyku-settings@example.org"
contact_email_to: ""

devise:
  account_signup: true
  # The address from which user invitations are sent
  invitation_from_email: "change-me-in-hyku-settings@example.org"

oai:
  name: Hyku
  url: http://example.org/catalog/oai
  prefix: oai:hyku
  email: change-me-in-hyku-settings@example.org
  sample_id: 806bbc5e-8ebe-468c-a188-b7c14fbe34df

bulkrax:
  enabled: false
