apiVersion: ENC[AES256_GCM,data:StM=,iv:Rug4Ouvh7JTfvNmecLXCGHiG/eIwPliZ5uunFG283T4=,tag:bFw1dWqyswbm5M0LAKX5vg==,type:str]
clusters:
    - cluster:
        server: ENC[AES256_GCM,data:Eu2Naa+++hHO4rUAEMnE0X//6DeFxc1tMzygcMymWISW2Cy6dIyvSszHxQ==,iv:n148HVxui/T6cREIiFFZNDQ3poISzsrvP6dAL+KQFHY=,tag:f2bghbN8FqBl1Vgq7sOUKQ==,type:str]
      name: ENC[AES256_GCM,data:jX9JwS1J+yBZPMabMPAgVTBGCw0=,iv:W7HnAdGdxP0Yot4pYWZQr3nZy50B3tVsxENMhrVn3wc=,tag:s7izZiKXJxNpJLffEj0AXQ==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:1q9ppYjTxTyXVwNDlQ2ajMXS0Sc=,iv:koidGWL0VJ9khNyrFi7gGpeANuhV6kZXh/YQ4o9fQKk=,tag:LWo//uQMcmH3C5pjYX+Zkw==,type:str]
        namespace: ENC[AES256_GCM,data:DmWi,iv:wWf+wSZ/JSjKmQVZJn2yINy0gRef8xnXZ7BiFQZL5mI=,tag:dUrC8lEMzA0PyMJtxxrJ7w==,type:str]
        user: ENC[AES256_GCM,data:unNtDQ02ZJGdY27mBJxMQKCgjAI=,iv:WX6bByXonjuToqECLbNXaDsLHwHmnNaq/iqFXSZJpNY=,tag:8X69hJck1VUzQMhJ/M7d9Q==,type:str]
      name: ENC[AES256_GCM,data:S869k5Mn/mNl0ZLVfg9xs+NA1Y4=,iv:3RfUYCgam+SK0PTns/cctoX+s6xnSXjsSkvhorEzOG8=,tag:0j8gNyhh6ybF/+r/kLvEEw==,type:str]
current-context: ENC[AES256_GCM,data:IoZC5VVhNSWYkjV6htRB83hVvGc=,iv:LUcb5ubq/MqW2fRIY3OJdQHM5TCp6y5BiHLW4cNo3xc=,tag:B2qEM//nd63j4N0GzTG0tg==,type:str]
kind: ENC[AES256_GCM,data:hvIFBTJ8,iv:cDj1Ro1YSwfNNIFlKfdi/AL0LNJ6vggFfDiWccsA/CE=,tag:zst9yH84unChn2T3+KUjAQ==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:k+uAB39rsfoi5u/svis6pPk6dl4=,iv:qe9iORXk5RZ2E3+SVGTTHDadnLx/v+3phkDPwqLZ7Rw=,tag:OTKNaPqeTdGB4aR3tnHyRQ==,type:str]
      user:
        token: ENC[AES256_GCM,data:Lw4toa3rq79KOQ636tEZUmfOrJggNu7DBrk96NWmBprraXfH5+gb6vmTV/rK0SB+/ezq6OgqzTYMRckeR12NtkiLUeHgx3CweafArQ==,iv:XOthNlySafLTeUnTmtyYBO48rmvTsvDIolzJCNd/9MA=,tag:QnPM4a9VkntFvjir5JueBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-20T17:22:36Z"
    mac: ENC[AES256_GCM,data:wpTRdw9x+Tm6f1YKdzNLnQcZTMcjqmgRWj0w05KPvXb+0vfoXsQipFzH4LvzsQAj71rNsI6K1qvERboPZsbPqUWtzVu4fnkpXvRnlnbTXcqKQnRCJnuYyqoIviJTPsuZ14+dHFl89Ov2D0Gsf8xPXiLBAYA7Vjd3yq3wJy2hILk=,iv:RMzhPVwudM3SZosVnnzmMdgXSx4z5Ok3pW42FAClhaU=,tag:SpH2xGSPgLMeAGWedEn4WA==,type:str]
    pgp:
        - created_at: "2022-07-20T17:22:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAyipFqBchOAqARAANPP1vGvr6zAO03qhMVSR7UmPQYHgJolmWhnujw3gduJR
            mJAH6iu4JowafAHZrd0OqBIFgidwQRoBnXpMMdV+4VgVnAkPzxDhkoRYM9zSgtml
            VrWAt/CZgQwZPJ5zWr0X9gX5w+SBkjRzsDTpGVTb663rau+NoyKklI8HVusEPI7P
            A1GPFVgAZGzrJ8vrxfO2AmgmvurZEg+vpA3SDS4Xefbdb4TkU/zPdNwaS+DS/o0s
            fDw284IMSy0x9jpOffIc9WrViPP/2JSRvJXWTvKqRvg1bwY8hR+nBz2C/KP5bLMM
            De2jzJHJNq2+JNxTFBuxlUhC3GC7aCGPrtd7NTnqC6vcaBQupE/NmbA58nqhfREd
            imPKw6OJDXP2vSviJPKyHyWZyOwtuOAsvd52tz+96CbdGmOpJFT3q89mwDATHBKa
            v/2B9pSE4XJHT2DLoSLkFhHurzkwdSwM+oi+WOthpsVkUtYl2aEYMAmCy0EiWOq9
            a0r9Sp/taxofMBzxC6NIqrQd5RdYPVN85qY+ZRfj3TBcPy9dEavYG6tMO/MrJBri
            3oK/zQUQ4ZQb4MTPFHnQEpR67d1mK80uX8p2nlohHSjBy6pFuguPq2Nt5DRz6VIp
            aAvj/qi/Ny6NMLL7RS/KuMpFOqsG8UneV6549UKVs77Y89N0iGVpJagFtwpDR4jS
            5gGsTw696twoFR32u2hpQ+dUayvmTdnacWO687U/kSs/xSh6b/WawRnjuvCRvTUm
            S5+r0EbSe7+AvQgxCRgjvcrkuB9YuJL4D6OX7JY7WXRUwOLezuZAAA==
            =cp/b
            -----END PGP MESSAGE-----
          fp: FD9645989F8F5113C93F7E8C1585560D0A87BA6A
    unencrypted_suffix: _unencrypted
    version: 3.7.2
