# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include SlugMetadata
  include AdventistMetadata
  self.indexer = CollectionIndexer

  def after_update_nested_collection_relationship_indices
    Rails.logger.error "skipping extra indexing for faster import"
  end
end
