# frozen_string_literal: true

# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  property :override_default_thumbnail,
           predicate: ::RDF::URI.intern('https://b2.adventistdigitallibrary.org/terms/overrideDefaultThumbnail'),
           multiple: false do |index|
             index.as :stored_searchable
           end

  include ::Hyrax::FileSetBehavior
end
