apiVersion: v1
data:
    .dockerconfigjson: $GITLAB_REGISTRY_TOKEN
kind: Secret
metadata:
    name: gitlab-registry
    namespace: $namespace
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
    .dockerconfigjson: $GITLAB_REGISTRY_TOKEN
kind: Secret
metadata:
    name: gitlab
    namespace: $namespace
type: kubernetes.io/dockerconfigjson
