replicaCount: 2

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

ingress:
  enabled: true
  hosts:
    - host: b2.adventistdigitallibrary.org
      paths:
        - path: /
    - host: "*.b2.adventistdigitallibrary.org"
      paths:
        - path: /

extraEnvVars:
  - name: SETTINGS__MULTITENANCY__ADMIN_HOST
    value: b2.adventistdigitallibrary.org
  - name: SETTINGS__MULTITENANCY__ROOT_HOST
    value: b2.adventistdigitallibrary.org
  - name: SETTINGS__MULTITENANCY__DEFAULT_HOST
    value: "%{tenant}.b2.adventistdigitallibrary.org"
  - name: SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION
    value: "false"
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/config"
  - name: INITIAL_ADMIN_EMAIL
    value: support@notch8.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: DATABASE_ADAPTER
    value: postgresql
  - name: DATABASE_HOST
    value:  samvera-alpha.cib2moxklxvd.us-east-1.rds.amazonaws.com
  - name: DATABASE_NAME
    value: adventist-production
  - name: DATABASE_USER
    value: postgres
  - name: FCREPO_BASE_PATH
    value: /adventist-production
  - name: FCREPO_HOST
    value: fcrepo.default.svc.cluster.local:8080
  - name: FCREPO_PATH
    value: /rest
  - name: FEDORA_URL
    value: http://fcrepo.default.svc.cluster.local:8080/rest
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:production@hyku-production-redis-master:6379/adventist
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hyku-production-redis-master
  - name: REDIS_URL
    value: redis://:staging@hyku-production-redis-master:6379/adventist
  - name: SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER
    value: sidekiq
  - name: SETTINGS__CONTACT_EMAIL
    value: support@notch8.com
  - name: SETTINGS__PRODUCTIONISE__INVITATION_FROM_EMAIL
    value: support@notch8.com
  - name: SETTINGS__FITS_PATH
    value: /app/fits/fits.sh
  - name: SETTINGS__MULTITENANCY__ADMIN_HOST
    value: b2.adventistdigitallibrary.org
  - name: SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION
    value: "true"
  - name: SETTINGS__MULTITENANCY__DEFAULT_HOST
    value: "%{tenant}.b2.adventistdigitallibrary.org"
  - name: SETTINGS__MULTITENANCY__ENABLED
    value: "true"
  - name: SETTINGS__SOLR__COLLECTION_OPTIONS__COLLECTION__CONFIG_NAME
    value: hyku-adventist
  - name: SETTINGS__SOLR__CONFIGSET
    value: hyku-adventist
  - name: SETTINGS__SOLR__URL
    value: http://admin:admin@solr.default:8983/solr/
  - name: SETTINGS__ZOOKEEPER__CONNECTION_STR
    value: solr-zookeeper-headless.default:2181/configs
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hyku-adventist-production
  - name: SOLR_CONFIGSET_NAME
    value: hyku-adventist-production
  - name: SOLR_HOST
    value: solr.default
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:admin@solr.default:8983/solr/
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_USER_NAME
    value: fc604e3b82d260
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_ADDRESS
    value: smtp.mailtrap.io
  - name: SMTP_DOMAIN
    value: smtp.mailtrap.io
  - name: SMTP_PORT
    value: "2525"
  - name: SMTP_TYPE
    value: cram_md5
  - name: SENTRY_DSN
    value: $SENTRY_DSN

worker:
  replicaCount: 1
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraEnvVars:
    - name: SETTINGS__MULTITENANCY__ADMIN_HOST
      value: b2.adventistdigitallibrary.org
    - name: SETTINGS__MULTITENANCY__ROOT_HOST
      value: b2.adventistdigitallibrary.org
    - name: SETTINGS__MULTITENANCY__DEFAULT_HOST
      value: "%{tenant}.b2.adventistdigitallibrary.org"
    - name: SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION
      value: "false"
    - name: CONFDIR
      value: "/app/samvera/hyrax-webapp/solr/config"
    - name: INITIAL_ADMIN_EMAIL
      value: support@notch8.com
    - name: INITIAL_ADMIN_PASSWORD
      value: testing123
    - name: DATABASE_ADAPTER
      value: postgresql
    - name: DATABASE_HOST
      value:  samvera-alpha.cib2moxklxvd.us-east-1.rds.amazonaws.com
    - name: DATABASE_NAME
      value: adventist-production
    - name: DATABASE_USER
      value: postgres
    - name: FCREPO_BASE_PATH
      value: /adventist-production
    - name: FCREPO_HOST
      value: fcrepo.default.svc.cluster.local:8080
    - name: FCREPO_PATH
      value: /rest
    - name: FEDORA_URL
      value: http://fcrepo.default.svc.cluster.local:8080/rest
    - name: IN_DOCKER
      value: "true"
    - name: LD_LIBRARY_PATH
      value: /app/fits/tools/mediainfo/linux
    - name: PASSENGER_APP_ENV
      value: production
    - name: RAILS_CACHE_STORE_URL
      value: redis://:production@hyku-production-redis-master:6379/adventist
    - name: RAILS_ENV
      value: production
    - name: RAILS_LOG_TO_STDOUT
      value: "true"
    - name: RAILS_MAX_THREADS
      value: "5"
    - name: RAILS_SERVE_STATIC_FILES
      value: "true"
    - name: REDIS_HOST
      value: hyku-production-redis-master
    - name: REDIS_URL
      value: redis://:staging@hyku-production-redis-master:6379/adventist
    - name: SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER
      value: sidekiq
    - name: SETTINGS__CONTACT_EMAIL
      value: support@notch8.com
    - name: SETTINGS__PRODUCTIONISE__INVITATION_FROM_EMAIL
      value: support@notch8.com
    - name: SETTINGS__FITS_PATH
      value: /app/fits/fits.sh
    - name: SETTINGS__MULTITENANCY__ADMIN_HOST
      value: b2.adventistdigitallibrary.org
    - name: SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION
      value: "true"
    - name: SETTINGS__MULTITENANCY__DEFAULT_HOST
      value: "%{tenant}.b2.adventistdigitallibrary.org"
    - name: SETTINGS__MULTITENANCY__ENABLED
      value: "true"
    - name: SETTINGS__SOLR__COLLECTION_OPTIONS__COLLECTION__CONFIG_NAME
      value: hyku-adventist
    - name: SETTINGS__SOLR__CONFIGSET
      value: hyku-adventist
    - name: SETTINGS__SOLR__URL
      value: http://admin:admin@solr.default:8983/solr/
    - name: SETTINGS__ZOOKEEPER__CONNECTION_STR
      value: solr-zookeeper-headless.default:2181/configs
    - name: SOLR_ADMIN_USER
      value: admin
    - name: SOLR_COLLECTION_NAME
      value: hyku-adventist-production
    - name: SOLR_CONFIGSET_NAME
      value: hyku-adventist-production
    - name: SOLR_HOST
      value: solr.default
    - name: SOLR_PORT
      value: "8983"
    - name: SOLR_URL
      value: http://admin:admin@solr.default:8983/solr/
    - name: SMTP_ENABLED
      value: "true"
    - name: SMTP_USER_NAME
      value: fc604e3b82d260
    - name: SMTP_PASSWORD
      value: $SMTP_PASSWORD
    - name: SMTP_ADDRESS
      value: smtp.mailtrap.io
    - name: SMTP_DOMAIN
      value: smtp.mailtrap.io
    - name: SMTP_PORT
      value: "2525"
    - name: SMTP_TYPE
      value: cram_md5
    - name: SENTRY_DSN
      value: $SENTRY_DSN

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

imagePullSecrets:
  - name: gitlab

fcrepo:
  enabled: false
postgresql:
  enabled: false
redis:
  cluster:
    enabled: false
  password: staging
solr:
  enabled: false

externalFcrepoHost: fcrepo.default.svc.cluster.local
externalPostgresql:
  host: samvera-alpha.cib2moxklxvd.us-east-1.rds.amazonaws.com
  username: postgres
  password: $RDS_PASSWORD

externalSolrHost: solr.default.cluster.local
externalSolrUser: admin
externalSolrPassword: admin
externalSolrCollection: "hyku-adventist-production"
