name: "Build Lint Test"
# run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
run-name: Testing SHA# ${{ github.sha:0:8 }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@adl-update-build
    secrets: inherit
    with:
      platforms: "linux/amd64"
      webTarget: hyku-web
      workerTarget: hyku-worker
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@adl-update-build
    with:
      confdir: "/app/samvera/hyrax-webapp/solr/config"
      webTarget: true
      workerTarget: true
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@adl-update-build
    with:
      webTarget: true
      workerTarget: true
