name: "Build Test Lint"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: scientist-softserv/build-lint-test-action/.github/workflows/build-test-lint.yaml@main