name: "Build Lint Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build-web:
    uses: scientist-softserv/actions/.github/workflows/build-web.yaml@arm-wrestle
    secrets: inherit
    with:
      target: hyku-base
  build-web-arm64:
    uses: scientist-softserv/actions/.github/workflows/build-web-arm64.yaml@arm-wrestle
    secrets: inherit
    with:
      target: hyku-base
  build-worker:
    uses: scientist-softserv/actions/.github/workflows/build-worker.yaml@arm-wrestle
    secrets: inherit
    with:
      target: hyku-worker
  build-worker-arm64:
    uses: scientist-softserv/actions/.github/workflows/build-worker-arm64.yaml@arm-wrestle
    secrets: inherit
    with:
      target: hyku-worker
  test:
    needs: [build-web, build-worker]
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.5
    with:
      worker: true
  lint:
    needs: [build-web, build-worker]
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.5
    with:
      worker: true
