name: "Build Test Lint"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v005-but-on-github-runners
