name: "Cleanup PR Registry Images"
run-name: Pruned ${{ github.event.pull_request.head.sha }}
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  purge-image:
    uses: scientist-softserv/actions/.github/workflows/cleanup-pr-registry-images.yaml@add-prune-ghcr-images-after-merge-to-main
    secrets: inherit
    with:
      image_name: adventist-dl
      webImage: true
      workerImage: true
