name: "Cleanup PR Registry Images"
run-name: Pruned ${{ github.event.pull_request.head.sha }}
on:
  push:
    branches:
      - main

jobs:
  delete-image:
    uses: scientist-softserv/actions/.github/workflows/cleanup-pr-registry-images.yaml@add-prune-ghcr-images-after-merge-to-main
    secrets: inherit
    with:
      webImage: true
      workerImage: true