name: "Deploy softserv staging cluster"
run-name: Deploy (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  call-workflow:
    uses: scientist-softserv/deploy-action/.github/workflows/deploy.yaml@main
    with:
      k8s-release-name: hyku-${{ inputs.environment }}
      k8s-namespace: adl-${{ inputs.environment }}
    secrets: inherit
