name: "Deploy adventist cluster"
run-name: Deploy (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  call-workflow:
    uses: scientist-softserv/actions/.github/workflows/deploy.yaml@v0.0.15
    with:
      k8s-release-name: hyku-${{ inputs.environment }}
      k8s-namespace: ${{ inputs.environment }}
      deploy-solr-image: false
    secrets: inherit
