name: "Build Solr"
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@adl-update-build
    secrets: inherit
    with:
      platforms: "linux/amd64"
      solrTarget: hyku-solr
